name: HelloWorldPlugin
version: 1.0
api-version: 1.13
main: de.joeakeem.plugin.Main

commands:
  reich:
    description: Macht dich reich!
  hack:
    description: Eine neue Diamanten-Spitzuhacke
  bogen:
    description: Ein neuer Bogen!
  pfeil:
    description: 64 neue Pfeile!